= :rocket: Asciidoctor Remote Include Processor Extension
:uri-asciidoctorjs: https://github.com/asciidoctor/asciidoctor.js

ifdef::env-github[]
image:https://github.com/feelpp/asciidoctor-remote-include-processor/workflows/npm-publish/badge.svg[npm-publish]
image:https://img.shields.io/npm/v/@feelpp/asciidoctor-remote-include-processor[npmjs version, link=https://www.npmjs.com/package/@feelpp/asciidoctor-remote-include-processor]
endif::[]

An extension for {uri-asciidoctorjs}[Asciidoctor.js] that allows to include remote files.

This is useful in antora.org[Antora] which does not enable this asciidoctor feature, see discussion https://gitlab.com/antora/antora/-/issues/246[here].

== Install

Install the dependencies:

    $ npm install asciidoctor.js asciidoctor-remote-include-processor

== Usage

=== Register as an Asciidoctor extension in the Antora playbook of your website

[source,yaml]
----
asciidoc:
  extensions:
  - "@feelpp/asciidoctor-remote-include-extension"
----

=== Include a remote file

In an Antora adoc page, include a remote file

```adoc
[source,cpp]
----
include::https://raw.githubusercontent.com/feelpp/asciidoctor-remote-include-processor/master/test/helloworld.cpp[]
----
```

----
.code here
[source,cpp]
----
include::https://raw.githubusercontent.com/feelpp/feelpp/develop/feelpp/quickstart/qs_laplacian.cpp[tag=env]
----
----

More details are available in the https://feelpp.github.io/asciidoctor-remote-include-processor/adoc-rip/latest/index.html[documentation].

== Acknowledgments

* https://github.com/djencks[@Djenks] on Gitter Antora/users for his many suggestions and explanations
* https://github.com/Mogztter[@Mozgtter] for https://github.com/Mogztter/asciidoctor-emoji[asciidoctor-emoji] which served as the template for this extension

and of course

* https://github.com/mojavelinux[@mojavelinux] for the awesome work he does on {antora} and {adoc}.