= Asciidoctor Remote Include Processor Extension
:stem: latexmath
:uri-asciidoctorjs: https://github.com/asciidoctor/asciidoctor.js
:uri-antora: https://docs.antora.org
:antora: {uri-antora}[Antora]
:uri-asciidoctor: https://www.asciidoctor.org
:adoc: {uri-asciidoctor}[Asciidoctor]

An extension for {uri-asciidoctorjs}[Asciidoctor.js] that allows to include remote files in {antora}.

This is useful in {antora} which does not enable this asciidoctor feature, see discussion https://gitlab.com/antora/antora/-/issues/246[here].

== Install

Install the dependencies:

    $ npm install asciidoctor.js asciidoctor-remote-include-processor

== Usage

=== Register as an Asciidoctor extension in the Antora playbook of your website

[source,yaml]
----
asciidoc:
  extensions:
  - "@feelpp/asciidoctor-remote-include-extension"
----

=== Include a remote file

In an Antora adoc page, include a remote file

++++
<pre><code class="language-cpp">
[source,cpp]
----
include::https://raw.githubusercontent.com/feelpp/asciidoctor-remote-include-processor/master/test/helloworld.cpp[]
----
</code>
</pre>
++++

which gives:

[source,cpp]
----
include::https://raw.githubusercontent.com/feelpp/asciidoctor-remote-include-processor/master/test/helloworld.cpp[]
----

=== Include a remote file partially using tags

In Asciidoctor we can include a source file partially using tags, see https://asciidoctor.org/docs/user-manual/#by-tagged-regions[here]. 
The extension enables this very feature.

++++
<pre>
<code class="language-cpp">
[source,cpp]
----
include::https://raw.githubusercontent.com/feelpp/asciidoctor-remote-include-processor/master/test/helloworld.cpp[tag=hello]
----
</code>
</pre>
++++

which gives:

[source,cpp]
----
include::https://raw.githubusercontent.com/feelpp/asciidoctor-remote-include-processor/master/test/helloworld.cpp[tag=hello]
----

// === Include a remote file partially using line ranges
// 
// In Asciidoctor we can include a source file partially using line ranges, see https://asciidoctor.org/docs/user-manual/#by-line-ranges[here]. 
// The extension enables this very feature.
// 
// ++++
// <pre>
// <code class="language-cpp">
// [source,cpp]
// ----
// include::https://raw.githubusercontent.com/feelpp/asciidoctor-remote-include-processor/master/test/helloworld.cpp[lines=3..8]
// ----
// </code>
// </pre>
// ++++
// 
// which gives:‡
// 
// [source,cpp]
// ----
// include::https://raw.githubusercontent.com/feelpp/asciidoctor-remote-include-processor/master/test/helloworld.cpp[lines=3..8]
// ----

== Acknowledgments

* https://github.com/djencks[@Djenks] on Gitter Antora/users for his many suggestions and explanations
* https://github.com/Mogztter[@Mozgtter] for https://github.com/Mogztter/asciidoctor-emoji[asciidoctor-emoji] which served as the template for this extension

and of course

* https://github.com/mojavelinux[@mojavelinux] for the awesome work he does on {antora} and {adoc}.